//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TesteOriginarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usu { get; set; }
        public string nome { get; set; }
        public string nm_img1 { get; set; }
        public byte[] vb_img1 { get; set; }
        public string nm_img2 { get; set; }
        public byte[] vb_img2 { get; set; }
        public string email { get; set; }
    }
}
